import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font from Google
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer-Section/Footer";
import Providers from "@/Provider/Provider";
import { ClerkProvider } from "@clerk/nextjs";
import StripeProvider from "@/StripeProvider/StripeProvider";
// import ChatIcon from "./components/Chat_Bot_Icon/Chat_Bot_Icon";

// Configure Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Specify font subsets
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include font weights
  variable: "--font-poppins", // Set a CSS variable for the font
});

export const metadata: Metadata = {
  title: "FurnitureHaven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
      
    
      <html lang="en" className={poppins.variable}>
        
      
      <body className="antialiased">
        
      <StripeProvider>
      <Providers>
        
        <Navbar />
        {children}
        <Footer />
        </Providers>
        </StripeProvider>
        {/* <ChatIcon /> */}

      </body>
    </html>
   
    </ClerkProvider>
  );
}
